
# NumPy Fundamentals Exercise

In this notebook, we will explore the basics of NumPy arrays including:
- Creating arrays
- Checking data types
- Working with multi-dimensional arrays
- Using slicing and transpose


In [29]:
import numpy as np


## Array Basics

In [30]:

fruits = ["apple", "banana", "cherry", "date"]
print(fruits)


['apple', 'banana', 'cherry', 'date']


In [31]:

arr_1 = np.array(fruits)
print(arr_1)


['apple' 'banana' 'cherry' 'date']


In [32]:

print(arr_1.dtype)

# Explanation:
# The dtype shows the type of elements stored in the array.
# 'U' means Unicode string.
# The number (like U6) represents the maximum lengt


<U6


In [33]:

arr_2 = np.array([[10, 11, 12],
                  [13, 14, 15]])

print(arr_2)


[[10 11 12]
 [13 14 15]]


In [34]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [35]:

print(arr_2)

# This shows that using .T does NOT change the original array.
# It only returns a transposed view.


[[10 11 12]
 [13 14 15]]


In [36]:


arr_3 = np.array([[1, 3, 5],
                  [2, 4, 6]])

print(arr_3)


[[1 3 5]
 [2 4 6]]


In [37]:

arr_4 = np.array([
    arr_3[0, 2],
    arr_3[1, 1]])

print(arr_4)


[5 4]


In [38]:

arr_5 = np.ones((2, 2, 2))
print(arr_5)



[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
