# Exercise 1.A NumPy: Manipulating Arrays

In [3]:
import numpy as np

## Looping Through Arrays

In [4]:

arrA = np.array([[11, 12, 13],
                 [14, 15, 16]])
print(arrA)


[[11 12 13]
 [14 15 16]]


In [5]:

for x in arrA:
    print(x * 2)


[22 24 26]
[28 30 32]


In [7]:

for x in arrA:
    for y in x:
        print(y * 2)


22
24
26
28
30
32



The first loop goes through rows (arrays) and multiplies entire rows by 2.
The second loop goes through each individual value and multiplies each element by 2 one at a time.


## Joining and Stacking Arrays

In [8]:

joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)


[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [9]:

joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)


[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [10]:

stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)


[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [12]:

try:
    stacked_array_2 = np.stack((joined_array_1, joined_array_2))
    print(stacked_array_2)
except Exception as e:
    print(e)

# Error happens because arrays have different shapes and cannot be stacked.


all input arrays must have the same shape


In [13]:

another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array_)


NameError: name 'another_joined_array_' is not defined

In [14]:

try:
    another_2 = np.concatenate((joined_array_1, arrA), axis=1)
    print(another_2)
except Exception as e:
    print(e)

# Er


all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2


In [15]:

h_stack = np.hstack((arrA, arrA))h_stack = np.hstack horizontally (side by side)

v_stack = np.vstack((arrA, arrA))
print(v_stack)
# vstack joins arrays vertically (on top of each other)

d_stack = np.dstack((arrA, arrA))
print(d_stack)
# dstack stacks arrays along a third dimension (depth)

print(h_stack)


SyntaxError: invalid syntax (1881872187.py, line 1)

## Splitting Arrays

In [ ]:

splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# This creates 2 arrays, each with the same number of columns.


In [ ]:

pliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# This creates 3 arrays; sizes may not be equal.


In [ ]:
## Searching and Replacing Array Values

In [16]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd

SyntaxError: unterminated string literal (detected at line 1) (2728924751.py, line 1)


## Sorting and Filtering Arrays


In [18]:

arrB = np.array([[7, 6],
                 [13, 5],
                 [7, 3]])

arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]
