# Exercise 1.B NumPy Random

In [2]:
import numpy as np


## Generating Random Numbers


In [3]:
r_1 = np.random.randint(1, 21, size =2)
print(r_1)

[ 5 16]


In [5]:
r_2= np.random.randint(1,21, size=(1, 2))
print(r_2)

[[ 9 18]]


In [7]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.26809   ]
 [0.83711689]]


In [8]:
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)


[[ 37  85  41  81  81]
 [ 44  37  57  63  78]
 [ 69  22  46  41  77]
 [ 51 100  94  66  73]]


In [10]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.72487866 0.69291495 0.77940757 0.72338239 0.17886023]
 [0.979504   0.88572097 0.03969684 0.95429268 0.65873664]
 [0.85118781 0.58435882 0.24166323 0.83725561 0.23400768]
 [0.62005549 0.10137766 0.48915221 0.31045976 0.4820453 ]]


## Generating Random Choices from an Array

In [21]:

students = np.array([
    "Alexus","Naomi","Alondra","Daniel","Corey","Lorah",
    "Blake","Luis","Charles","Sonia","Hana","Smaya"
])
print(students)


['Alexus' 'Naomi' 'Alondra' 'Daniel' 'Corey' 'Lorah' 'Blake' 'Luis'
 'Charles' 'Sonia' 'Hana' 'Smaya']


In [22]:
call_on = np.random.choice(students)
print(call_on)


Alondra


In [23]:

call_on = np.random.choice(students)
print(call_on)


Luis


In [24]:

call_on = np.random.choice(students)
print(call_on)


Charles


In [25]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

# This may not be effective because the same student can appear multiple times
# and some students might not be select


[['Hana' 'Sonia' 'Corey' 'Alondra']
 ['Luis' 'Blake' 'Lorah' 'Charles']
 ['Sonia' 'Lorah' 'Sonia' 'Alexus']]


In [26]:

breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)


[['Alexus' 'Sonia' 'Alondra' 'Smaya']
 ['Naomi' 'Daniel' 'Sonia' 'Alexus']
 ['Lorah' 'Naomi' 'Lorah' 'Smaya']]


In [29]:

probabilities = [0.1, 0.1, 0.05, 0.05, 0.1, 0.1, 0.3, 0.0, 0.05, 0.05, 0.05, 0.05]

call_on_weighted = np.random.choice(students, size=5, p=probabilities)
print(call_on_weighted)

['Blake' 'Lorah' 'Blake' 'Smaya' 'Blake']



## Generating a Normal Distribution


In [30]:

bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)


[[ 7.10205016e+00 -2.36691047e+00  1.13066437e+01  1.54857375e+01
   2.06450700e+00]
 [ 9.23527684e+00  1.35340364e+01  1.84462822e+01  8.54452710e+00
   1.40512374e-02]
 [ 2.11845910e+01  1.20668577e+01  4.74742106e+00  7.47420394e+00
   1.35896716e+01]
 [ 7.06858421e+00  1.33185562e+01  9.24354394e+00  1.06010626e+01
   1.59858364e+01]]
