# Exercise 1.A NumPy: Manipulating Arrays


In [2]:
import numpy as np

# Looping Through Arrays

In [3]:
# Create arrA 
arrA = np.array([[11,12,13], [14,15,16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [6]:
# Loop through the first dimension
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
# Loop through the second dimension 
for x in arrA:
    for y in x:
        print(y * 2)


22
24
26
28
30
32


# The first loop does the function from left to right vs the second from top to bottom

In [9]:
# Loop through second dimension with loop_result
for x in arrA:
    for y in x: 
        loop_result = x * 2
        print(loop_result)

# Prints tow multiplied by 2 repeated because X (row) is used instead of y (the individual element)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [15]:
# Concatenate on axis 0
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [10]:
# Concatenate on axis 1
joined_array_2 = np.concatenate((arrA, arrA),axis =1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [16]:
# Stack arrays (default axis=0)
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)


[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [17]:
# Attempt stacking mismatched shapes
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

# Error occurs because the arrays have different shapes and cannot be stacked together


ValueError: all input arrays must have the same shape

In [18]:

# Concatenate joined_array_1 with arrA
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)


[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [19]:

# Concatenate on axis 1 (will error)
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

# Error occurs because the number of rows does not match for axis=1 concatenation.


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2


# Using stacking helper functions
h_stack = np.hstack((arrA, arrA))  # stacks horizontally (side by side)
v_stack = np.vstack((arrA, arrA))  # stacks vertically (on top)
d_stack = np.dstack((arrA, arrA))  # stacks depth-wise (adds a third dimension)

print(h_stack)
print(v_stack)
print(d_stack)



## Splitting Arrays


In [22]:

# Split into 2
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# This creates 2 arrays, each still 2D.


[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [23]:

# Split into 3
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# This creates 3 arrays; they are still 2D but may not be evenly sized.


[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]



## Searching and Replacing Array Values


In [24]:

# Use where() for even numbers
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)


[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays


In [26]:

# Create arrB and sort
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)


[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [27]:

# Filter values less than 7
print(arrB)

z = arrB < 7
arrC = arrB[z]

print(arrC)


[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [28]:

# Filter values greater than or equal to 7
y = arrB >= 7
arrD = arrB[y]

print(arrD)


[ 7 13  7]
